### ISSUE TITLE
New user cannot authenticate

### ISSUE THREAD

**Issue by JeffreyAReyes** [CodeWithDennis/larament#22]
Hi. I cloned larament in my development laptop, and logged-in using the seeded user. I added new user, and when i tried to login with new user credentials, it cannot authenticate:

![image](https://github.com/user-attachments/assets/0ad3fdb2-d962-4193-b4c7-6f03c10aca40)

**Comment by CodeWithDennis** [comment]
The default user is located in the user seeder file, if you change that you also need to change the custom login file located in the Filament directory.
