### ISSUE TITLE
Implement MustVerifyEmail

### ISSUE THREAD

**Issue by bhattji** [CodeWithDennis/larament#24]
this is great, 

Can you please Implement Illuminate\Contracts\Auth\MustVerifyEmail ?

**Comment by CodeWithDennis** [comment]
I don't want to make this mandatory in the boilerplate. It's already included (commented out) and ready for use whenever you need it.

**Comment by bhattji** [comment]
Can you please explain, the places to uncomment?

Thanks in advance

**Comment by CodeWithDennis** [comment]
https://laravel.com/docs/11.x/verification

**Comment by bhattji** [comment]
Route [filament.admin.auth.email-verification.verify] not defined.

is the bollerplate has these necessary routes? and blade views?

**Comment by CodeWithDennis** [comment]
> Route [filament.admin.auth.email-verification.verify] not defined.
> 
> is the bollerplate has these necessary routes? and blade views?

https://filamentphp.com/docs/3.x/panels/users#authentication-features
