### ISSUE TITLE
[BUG] navigationiGroup not work

### ISSUE THREAD

**Issue by muhazmi** [CodeWithDennis/larament#48]
Hi, Dennis. I love your work. I've problem with applying navigationGroup. Why the menus in Finance and Master not showing?

![image](https://github.com/user-attachments/assets/9004514c-b2c0-4257-b98b-710770c2bfe2)

![image](https://github.com/user-attachments/assets/4bed3c19-571b-412a-bce5-a94fcf77458c)

**Comment by CodeWithDennis** [comment]
I can see the menu groups in your menu. But this isn’t a **Larament** issue; it’s more of a FilamentPHP question. You might want to try asking in the Filament official Discord's help channel.

**Comment by muhazmi** [comment]
btw, i've tried that without use larament and it work normally

**Comment by CodeWithDennis** [comment]
> btw, i've tried that without use larament and it work normally

![Scherm­afbeelding 2024-11-08 om 14 37 42](https://github.com/user-attachments/assets/0d837dbb-2e97-4651-95c7-791496c33a98)

**Comment by muhazmi** [comment]
i've found the problem, i just run composer update and problem solved.
![image](https://github.com/user-attachments/assets/513c1401-28a5-41fa-8b95-f429c0191b47)
